repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]

      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--py38-plus]
